version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the build phase"
  build:
    run-as: Linux-user-name
    commands:
      - echo "in build block"
      - echo "running some tests---mk"
      - grep -fq "india123" readme.txt
  post_build:
    commands:
      - echo "in the post-build phase"
