# Generated by Django 2.1.2 on 2018-10-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0002_auto_20181029_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzseries',
            name='cardtype',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
