# Generated by Django 2.1.2 on 2018-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0003_amzseries_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzseries',
            name='cards_requirement',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='amzseries',
            name='start_series',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
