# Generated by Django 2.1.2 on 2018-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0005_auto_20181030_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmzOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(default=0, max_length=20)),
                ('total_cards_requirement', models.CharField(default=0, max_length=20)),
                ('start_series', models.CharField(default=0, max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='amzseries',
            name='cardtype',
        ),
        migrations.RemoveField(
            model_name='amzseries',
            name='start_series',
        ),
        migrations.RemoveField(
            model_name='amzseries',
            name='total_cards_requirement',
        ),
    ]
