# Generated by Django 2.1.2 on 2018-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0006_auto_20181030_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzorder',
            name='end_series',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
