# Generated by Django 2.1.2 on 2018-10-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0008_auto_20181030_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amzorder',
            name='end_series',
        ),
    ]
