# Generated by Django 2.1.2 on 2018-10-30 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0010_auto_20181030_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmzOrder',
        ),
        migrations.AddField(
            model_name='amzseries',
            name='cardtype',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='amzseries',
            name='end_series',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='amzseries',
            name='start_series',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator('\\d{16,16}', 'Number must be 16 digits')]),
        ),
        migrations.AddField(
            model_name='amzseries',
            name='total_cards_requirement',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='amzseries',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
